# Generated by Django 5.0.6 on 2024-08-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_address_profile_street_address_profile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_no',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
