# Generated by Django 5.0.6 on 2024-08-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deposit',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='withdraw',
            field=models.IntegerField(default=0.0),
        ),
    ]
