# Generated by Django 5.0.6 on 2024-08-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_deposit_profile_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='transfer',
            field=models.IntegerField(default=0.0),
        ),
    ]
