# Generated by Django 5.0.6 on 2024-08-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_transactions_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='message',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
