# Generated by Django 5.0.6 on 2024-08-30 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_transaction_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='loan',
            field=models.IntegerField(default=0.0),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='accounts.profile')),
            ],
        ),
    ]
