# Generated by Django 5.0.6 on 2024-08-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_loan_profile_loan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.IntegerField(default=0.0),
        ),
    ]
