# Generated by Django 5.0.6 on 2024-08-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_loan_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='pay',
            field=models.BooleanField(default=False),
        ),
    ]
