# Generated by Django 5.1.1 on 2024-11-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_quicktransfer_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tran_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
